source 'https://rubygems.org'

#gem 'aws-sdk-v1'
#gem 'aws-sdk', '~> 2'
gem 'cucumber', '~> 1.3.17'
#gem 'sinatra'
#gem 'savon'
gem 'syntax'
gem 'data_magic'
gem 'net-ssh'
gem 'net-sftp'
gem 'pretty_face'
gem 'minitest'
gem 'json'
gem 'rake'
gem 'jruby-pageant'
gem 'parseconfig'
gem 'nokogiri'
gem 'net-scp'
gem 'equivalent-xml'
gem 'bundler'
#gem 'test-framework'#, '1.1.0', :path => 'yourpath/acceptance_test_framework'
gem 'rest-client',  '1.6.7' #rest-client -v 1.6.7 install this gem
gem 'highline'
gem 'selenium-webdriver', '2.44.0'
gem 'pg'
gem 'pry'
gem 'rubyXL'
gem 'docker-api'
gem 'spreadsheet'